### ISSUE TITLE
Keybinding conflicts with Vim-Surround

### ISSUE THREAD

**Issue by ericboehs** [maxbrunsfeld/vim-yankstack#18]
Not sure how you'd handle this but your key bindings conflict with [tpope/vim-surround](http://github.com/tpope/vim-surround). Specifically visual line surround with the `S` key.

Example from his README:

```
<em>Hello</em> world!
```

Press a capital V (for linewise visual mode) followed by `S<p class="important">`.

```
<p class="important">
  <em>Hello</em> world!
</p>
```

With yankstack installed this just removes the visual block and puts you in insert mode.

**Comment by brookst** [comment]
I just ran into this and had a head scratch. The `yankstack#setup` function seems to be of no help since vim-surround is set up as, say, `pathogen#infect` is called. The `g:yankstack_map_keys` variable helps, if you leave out 'S', i.e. `let g:yankstack_yank_keys = ['c', 'C', 'd', 'D', 's', 'x', 'X', 'y', 'Y']`. But _only_ if you set it before `yankstack#setup` gets called (so before `pathogen#infect`).

I'll make a pull request to warn about this issue.
